name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Se actualiza cada hora
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TuUsuarioDeGitHub # <--- CAMBIA ESTO
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Argentina/Buenos_Aires # Ajusta tu zona horaria
          
          # Configuración para el calendario 3D (Isocalendar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # O half-year como en la imagen
          
          # Configuración para las estadísticas de commits (Habits)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
